[package]
name = "bytecode_interp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
bincode = "1.3.3"
bytecode = { path = "../bytecode" }
clap = { version = "3.0.14", features = ["derive"] }
entity = { path = "../entity" }
