[workspace]
members = [
    "components/ast",
    "components/ast_interp",
    "components/ast_to_bytecode",
    "components/bytecode",
    "components/bytecode_interp",
    "components/entity",
    "components/parser",
    "components/token",
]
