[workspace]
members = [
    "crates/ast",
    "crates/ast_interp",
    "crates/bytecode",
    "crates/bytecode_compiler",
    "crates/cli_ext",
    "crates/lexer",
    "crates/lsp_server",
    "crates/parser",
    "crates/token",
    "crates/vm",
]
