var sourcesIndex = {};
sourcesIndex["mylang_ast"] = {"name":"","files":["expr.rs","lib.rs","stmt.rs"]};
sourcesIndex["mylang_ast_interp"] = {"name":"","files":["entity.rs","lib.rs"]};
sourcesIndex["mylang_bytecode"] = {"name":"","files":["lib.rs"]};
sourcesIndex["mylang_bytecode_compiler"] = {"name":"","files":["lib.rs"]};
sourcesIndex["mylang_cli_ext"] = {"name":"","files":["command.rs","lib.rs","matches.rs","with_output.rs"]};
sourcesIndex["mylang_cli_test"] = {"name":"","files":["main.rs"]};
sourcesIndex["mylang_lexer"] = {"name":"","dirs":[{"name":"state","files":["i32.rs","str.rs","symbol.rs"]},{"name":"transition","files":["i32.rs","initial.rs","str.rs","symbol.rs"]}],"files":["lib.rs","result.rs","state.rs","transition.rs","with_pos.rs"]};
sourcesIndex["mylang_lsp_server"] = {"name":"","dirs":[{"name":"responder","files":["analyzer.rs","diagnostic.rs","handler.rs","range.rs"]}],"files":["lib.rs","message.rs","receiver.rs","responder.rs","sender.rs"]};
sourcesIndex["mylang_parser"] = {"name":"","dirs":[{"name":"parse","files":["expr.rs","program.rs","stmt.rs","term.rs"]}],"files":["lib.rs","parse.rs","result.rs"]};
sourcesIndex["mylang_token"] = {"name":"","files":["lib.rs","locatable.rs","pos.rs","range.rs"]};
sourcesIndex["mylang_vm"] = {"name":"","files":["entity.rs","lib.rs"]};
createSourceSidebar();
