[package]
name = "mylang_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.14", features = ["derive", "cargo"] }
itertools = "0.10.3"
mylang_ast = { path = "../ast" }
mylang_token = { path = "../token" }
serde_json = "1.0.79"
thiserror = "1.0.30"
