#!/bin/sh -ex

cargo build

parent_dir="$(realpath $(dirname "$0"))"

lex() {
    "${parent_dir}/../target/debug/lexer"
}

parse() {
    "${parent_dir}/../target/debug/parser"
}

to_bytecode() {
    "${parent_dir}/../target/debug/ast_to_bytecode"
}

execute() {
    "${parent_dir}/../target/debug/bytecode_interp"
}

cat hello.mylang | lex | parse | to_bytecode | execute
