[package]
name = "lsp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.12.0"
anyhow = "1.0.53"
env_logger = "0.9.0"
log = "0.4.14"
lsp = { path = "../lsp" }
serde_json = "1.0.78"

[dependencies.tokio]
version = "1.16.1"
features = ["io-std"]
