[package]
name = "mylang_lsp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
anyhow = "1.0.60"
env_logger = "0.9.0"
itertools = "0.10.3"
log = "0.4.17"
mylang_ast = { path = "../ast" }
mylang_lexer = { path = "../lexer" }
mylang_parser = { path = "../parser" }
mylang_token = { path = "../token" }
regex = "1.6.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
valq = "0.1.0"

[dependencies.tokio]
version = "1.20.1"
features = ["io-std"]
