[package]
name = "lsp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.12.0"
anyhow = "1.0.53"
ast = { path = "../ast" }
env_logger = "0.9.0"
lexer = { path = "../lexer" }
log = "0.4.14"
lsp = { path = "../lsp" }
regex = "1.5.4"
serde_json = "1.0.78"
token = { path = "../token" }
valq = "0.1.0"

[dependencies.tokio]
version = "1.16.1"
features = ["io-std"]
