[package]
name = "mylang_lsp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.0"
anyhow = "1.0.70"
env_logger = "0.10.0"
itertools = "0.10.5"
log = "0.4.17"
mylang_ast = { path = "../ast" }
mylang_lexer = { path = "../lexer" }
mylang_parser = { path = "../parser" }
mylang_token = { path = "../token" }
regex = "1.8.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
valq = "0.1.0"

[dependencies.tokio]
version = "1.28.1"
features = ["io-std"]
