[package]
name = "mylang_lsp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.12.0"
anyhow = "1.0.53"
mylang_ast = { path = "../ast" }
env_logger = "0.9.0"
itertools = "0.10.3"
mylang_lexer = { path = "../lexer" }
log = "0.4.14"
mylang_parser = { path = "../parser" }
regex = "1.5.4"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
mylang_token = { path = "../token" }
valq = "0.1.0"

[dependencies.tokio]
version = "1.16.1"
features = ["io-std"]
