[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
ast = { path = "../ast" }
clap = { version = "3.0.14", features = ["derive"] }
serde_json = "1.0.78"
thiserror = "1.0.30"
token = { path = "../token" }
utf8-chars = "1.0.2"
