[package]
name = "mylang_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.0.14", features = ["derive"] }
itertools = "0.10.3"
serde_json = "1.0.79"
thiserror = "1.0.30"
mylang_token = { path = "../token" }
utf8-chars = "1.0.2"

[dev-dependencies]
proptest = "1.0.0"
