[package]
name = "mylang_lexer"
authors = ["Kodai Matsumoto <nobita.0918@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
clap = { version = "4.0.15", features = ["cargo", "derive"] }
itertools = "0.10.5"
mylang_cli_ext = { path = "../cli_ext" }
mylang_token = { path = "../token" }
thiserror = "1.0.37"
utf8-chars = "2.0.2"

[dev-dependencies]
insta = "1.21.0"
