[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
clap = { version = "4.3.17", features = ["derive"] }
once_cell = "1.18.0"
serde = "1.0.173"
serde_json = "1.0.103"
