[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
bincode = "1.3.3"
clap = { version = "3.2.5", features = ["derive"] }
once_cell = "1.12.0"
serde = "1.0.137"
serde_json = "1.0.81"
