[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bincode = "1.3.3"
clap = { version = "3.1.14", features = ["derive"] }
once_cell = "1.10.0"
serde = "1.0.136"
serde_json = "1.0.79"
