[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
bincode = "1.3.3"
clap = { version = "4.2.7", features = ["derive"] }
once_cell = "1.17.1"
serde = "1.0.159"
serde_json = "1.0.96"
