[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
bincode = "1.3.3"
clap = { version = "3.2.14", features = ["derive"] }
once_cell = "1.13.0"
serde = "1.0.140"
serde_json = "1.0.82"
