[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
bincode = "1.3.3"
clap = { version = "4.0.27", features = ["derive"] }
once_cell = "1.16.0"
serde = "1.0.149"
serde_json = "1.0.89"
