[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.59"
bincode = "1.3.3"
clap = { version = "3.2.16", features = ["derive"] }
once_cell = "1.13.0"
serde = "1.0.141"
serde_json = "1.0.82"
