[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
bincode = "1.3.3"
clap = { version = "4.0.15", features = ["derive"] }
once_cell = "1.15.0"
serde = "1.0.145"
serde_json = "1.0.86"
