[package]
name = "mylang_cli_ext"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
bincode = "1.3.3"
clap = { version = "3.2.22", features = ["derive"] }
once_cell = "1.15.0"
serde = "1.0.143"
serde_json = "1.0.86"
