[package]
name = "mylang_bytecode_compiler"
version = "0.1.0"
edition = "2021"
description = "Compiler implementation for mylang that converts AST to bytecode"

[dependencies]
anyhow = "1.0.53"
bincode = "1.3.3"
clap = { version = "3.0.14", features = ["cargo"] }
mylang_ast = { path = "../ast" }
mylang_bytecode = { path = "../bytecode" }
mylang_cli_ext = { path = "../cli_ext" }
mylang_token = { path = "../token" }
serde_json = "1.0.79"

[dev-dependencies]
insta = "1.12.0"
