[package]
name = "mylang_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.55"
bincode = "1.3.3"
clap = { version = "3.1.4", features = ["cargo"] }
mylang_bytecode = { path = "../bytecode" }
mylang_cli_ext = { path = "../cli_ext" }
serde_json = "1.0.79"
thiserror = "1.0.30"

[dev-dependencies]
insta = "1.12.0"
