[package]
name = "mylang_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.60"
bincode = "1.3.3"
clap = { version = "3.2.16", features = ["cargo"] }
mylang_bytecode = { path = "../bytecode" }
mylang_cli_ext = { path = "../cli_ext" }
serde_json = "1.0.82"
thiserror = "1.0.32"

[dev-dependencies]
insta = "1.17.1"
