[package]
name = "mylang_vm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
bincode = "1.3.3"
mylang_bytecode = { path = "../bytecode" }
clap = { version = "3.0.14", features = ["derive"] }
thiserror = "1.0.30"

[dev-dependencies]
insta = "1.12.0"
