name: Doc

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/doc.yml"
      - "crates/**/*.rs"
      - "crates/**/Cargo.toml"
      - "Cargo.toml"
      - "Cargo.lock"
      - "rust-toolchain.toml"

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build doc
        run: cargo +nightly doc --no-deps --document-private-items
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
      - name: Deploy doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
