name: cargo-udeps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  check-sha:
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ !steps.check_sha.outputs.cache-hit }}

    steps:
      - uses: actions/checkout@v4

      - name: Create cache file
        run: |
          echo ${{ github.sha }} > github_sha.txt

      - name: Check SHA
        id: check_sha
        uses: actions/cache@v3
        with:
          path: github_sha.txt
          key: check-SHA-${{ github.sha }}

  udeps:
    runs-on: ubuntu-latest

    needs: check-sha

    if: needs.check-sha.outputs.should_run == 'true'

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-udeps

      - run: cargo +nightly udeps
