name: VS Code Extension

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/vscode-ext.yml"
      - "vscode-ext/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.30.0"
          run_install: true
      - run: pnpm build
        working-directory: vscode-ext
