name: VS Code Extension

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/vscode-ext.yml"
      - "vscode-ext/**/*"
      - "mylang.sln"
      - "paket.dependencies"
      - "paket.lock"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - run: |
          dotnet tool restore
          dotnet paket restore
          dotnet restore
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.29.1
          run_install: true
      - run: pnpm build
        working-directory: vscode-ext
