name: VS Code Extension

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/vscode-ext.yml"
      - "vscode-ext/**/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: "6.30.1"
          run_install: true
      - run: pnpm build
        working-directory: vscode-ext

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: "6.30.1"
          run_install: true
      - run: pnpm lint
        working-directory: vscode-ext

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: "6.30.1"
          run_install: true
      - run: pnpm format:check
        working-directory: vscode-ext
